#!/bin/sh

curl -s -O http://nodejs.org/dist/v0.10.22/node-v0.10.22-darwin-x64.tar.gz
tar -zxf node-v0.10.22-darwin-x64.tar.gz
export PATH=$PATH:node-v0.10.22-darwin-x64/bin/
echo "Fetched Node"

# Request releases
curl -s -O https://api.github.com/repos/atom/atom/releases -H 'Authorization: token 9a30c699f5f086e2f6d1ee24dabe4f3e5628f2b1'
node -e "fs = require('fs');console.log(JSON.parse(fs.readFileSync('releases'))[1].assets_url);" > release_url

# Request release
curl -s -O `cat release_url` -H 'Authorization: token 9a30c699f5f086e2f6d1ee24dabe4f3e5628f2b1'
node -e "fs = require('fs');console.log(JSON.parse(fs.readFileSync('assets'))[0].url);" > asset_url

# Request asset
echo "Fetching Atom..."
curl -s -L `cat asset_url` \
  -u '9a30c699f5f086e2f6d1ee24dabe4f3e5628f2b1:x-oauth-basic' \
  -H 'Accept: application/octet-stream' \
  -o atom.zip

mkdir atom
unzip -q atom.zip -d atom

echo "Grab dependencies"
atom/Atom.app/Contents/Resources/app/node_modules/.bin/apm update

echo "Running tests..."
atom/Atom.app/Contents/Resources/app/node_modules/.bin/apm test --path atom/Atom.app/Contents/Resources/app/atom.sh

exit
